# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20180408_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksection',
            name='stockId2',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
