# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stocksection_stockid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksection',
            name='sectionId',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
