# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_sectionmarketinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='decreaseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='increaseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='num',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='sectionIncreseVelo',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=32),
        ),
        #migrations.AlterField(
        #    model_name='sectionmarketinfo',
        #    name='sectionName',
        #    field=models.CharField(max_length=300, unique=True),
        #),
    ]
