# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_sectionmarketinfo_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='mostIncreaseIncreateRate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='mostIncreaseIncreateRateStr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='mostIncreaseStockId',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='mostIncreaseStockName',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
