# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stockcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectioninfo',
            options={'ordering': ('-sectionName',)},
        ),
        migrations.AlterModelOptions(
            name='stockcomment',
            options={'ordering': ('-like',)},
        ),
        migrations.AlterModelOptions(
            name='stocksection',
            options={'ordering': ('-sectionName',)},
        ),
    ]
