# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20180427_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockId', models.CharField(max_length=300)),
                ('stockName', models.CharField(max_length=300)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-priority',),
            },
        ),
    ]
