# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_importantstock_stockname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionIncreaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('sectionName', models.CharField(max_length=100, unique=True)),
                ('sectionIncreaseRate', models.DecimalField(decimal_places=10, max_digits=32)),
                ('sectionIncreaseRateStr', models.CharField(max_length=300)),
                ('sectionIncreaseSpeed2minRate', models.DecimalField(decimal_places=10, max_digits=32)),
                ('sectionIncreaseSpeed2minRateStr', models.CharField(max_length=300)),
                ('sectionIncreaseSpeed5MinRate', models.DecimalField(decimal_places=10, max_digits=32)),
                ('sectionIncreaseSpeed5MinRateStr', models.CharField(max_length=300)),
                ('sectionIncreaseSpeed30MinRate', models.DecimalField(decimal_places=10, max_digits=32)),
                ('sectionIncreaseSpeed30MinRateStr', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='StcokMarketIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('indexSH', models.DecimalField(decimal_places=10, max_digits=32)),
                ('indexIncreaseSH', models.DecimalField(decimal_places=10, max_digits=32)),
                ('indexIncreaseRateSH', models.DecimalField(decimal_places=10, max_digits=32)),
                ('increaseStockSH', models.IntegerField(default=0)),
                ('decreaseStockSH', models.IntegerField(default=0)),
                ('flatStockSH', models.IntegerField(default=0)),
                ('limitupStcokSH', models.IntegerField(default=0)),
                ('limitdownStcokSH', models.IntegerField(default=0)),
                ('longRedStcokSH', models.IntegerField(default=0)),
                ('longGreenStcokSH', models.IntegerField(default=0)),
                ('indexSZ', models.DecimalField(decimal_places=10, max_digits=32)),
                ('indexIncreaseSZ', models.DecimalField(decimal_places=10, max_digits=32)),
                ('indexIncreaseRateSZ', models.DecimalField(decimal_places=10, max_digits=32)),
                ('increaseStockSZ', models.IntegerField(default=0)),
                ('decreaseStockSZ', models.IntegerField(default=0)),
                ('flatStockSZ', models.IntegerField(default=0)),
                ('limitupStcokSZ', models.IntegerField(default=0)),
                ('limitdownStcokSZ', models.IntegerField(default=0)),
                ('longRedStcokSZ', models.IntegerField(default=0)),
                ('longGreenStcokSZ', models.IntegerField(default=0)),
                ('indexZXB', models.DecimalField(decimal_places=10, max_digits=32)),
                ('indexIncreaseZXB', models.DecimalField(decimal_places=10, max_digits=32)),
                ('indexIncreaseRateZXB', models.DecimalField(decimal_places=10, max_digits=32)),
                ('increaseStockZXB', models.IntegerField(default=0)),
                ('decreaseStockZXB', models.IntegerField(default=0)),
                ('flatStockZXB', models.IntegerField(default=0)),
                ('limitupStcokZXB', models.IntegerField(default=0)),
                ('limitdownStcokZXB', models.IntegerField(default=0)),
                ('longRedStcokZXB', models.IntegerField(default=0)),
                ('longGreenStcokZXB', models.IntegerField(default=0)),
                ('indexCYB', models.DecimalField(decimal_places=10, max_digits=32)),
                ('indexIncreaseCYB', models.DecimalField(decimal_places=10, max_digits=32)),
                ('indexIncreaseRateCYB', models.DecimalField(decimal_places=10, max_digits=32)),
                ('increaseStockCYB', models.IntegerField(default=0)),
                ('decreaseStockCYB', models.IntegerField(default=0)),
                ('flatStockCYB', models.IntegerField(default=0)),
                ('limitupStcokCYB', models.IntegerField(default=0)),
                ('limitdownStcokCYB', models.IntegerField(default=0)),
                ('longRedStcokCYB', models.IntegerField(default=0)),
                ('longGreenStcokCYB', models.IntegerField(default=0)),
                ('limitupStcokTotal', models.IntegerField(default=0)),
                ('limitupNormalStcokTotal', models.IntegerField(default=0)),
                ('limitupOneTypeStcokTotal', models.IntegerField(default=0)),
                ('limitupTTypeStcokTotal', models.IntegerField(default=0)),
                ('limitupFirstStcokTotal', models.IntegerField(default=0)),
                ('limitupSencondStcokTotal', models.IntegerField(default=0)),
                ('limitupThirdStcokTotal', models.IntegerField(default=0)),
                ('badLimitupStcokTotal', models.IntegerField(default=0)),
                ('badLimitupFirstStcokTotal', models.IntegerField(default=0)),
                ('badLimitupSencondStcokTotal', models.IntegerField(default=0)),
                ('badLimitupThirdStcokTotal', models.IntegerField(default=0)),
                ('limitdownStcokTotal', models.IntegerField(default=0)),
                ('limitdownFirstStcokTotal', models.IntegerField(default=0)),
                ('limitdownSencondStcokTotal', models.IntegerField(default=0)),
                ('limitdownThirdStcokTotal', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
