# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20180518_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmarketinfo',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='sectionName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sectionmarketinfo',
            name='sectionName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
