# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20180518_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIncreaseFastWithAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('stockId', models.CharField(max_length=32)),
                ('stockName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('stockId',),
            },
        ),
        migrations.CreateModel(
            name='StockLimitUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('stockId', models.CharField(max_length=32)),
                ('stockName', models.CharField(max_length=100)),
                ('limitUpInfo', models.CharField(max_length=100)),
                ('limitUpTime', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('stockId',),
            },
        ),
        migrations.AddField(
            model_name='stockmarketindex',
            name='indexIncreaseRateStrCYB',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockmarketindex',
            name='indexIncreaseRateStrSH',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockmarketindex',
            name='indexIncreaseRateStrSZ',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockmarketindex',
            name='indexIncreaseRateStrZXB',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='sectionIncreaseRate',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='sectionIncreaseSpeed2minRate',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='sectionIncreaseSpeed30MinRate',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='sectionIncreaseSpeed5MinRate',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexCYB',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexIncreaseCYB',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexIncreaseSH',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexIncreaseSZ',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexIncreaseZXB',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexSH',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexSZ',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexZXB',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
