# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_auto_20180522_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='sectionIncreaseRate',
            field=models.DecimalField(decimal_places=10, max_digits=32),
        ),
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='sectionIncreaseSpeed2minRate',
            field=models.DecimalField(decimal_places=10, max_digits=32),
        ),
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='sectionIncreaseSpeed30MinRate',
            field=models.DecimalField(decimal_places=10, max_digits=32),
        ),
        migrations.AlterField(
            model_name='sectionincreaseinfo',
            name='sectionIncreaseSpeed5MinRate',
            field=models.DecimalField(decimal_places=10, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexIncreaseRateCYB',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexIncreaseRateSH',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexIncreaseRateSZ',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketindex',
            name='indexIncreaseRateZXB',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
