# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20180522_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantStockMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockId', models.CharField(max_length=30)),
                ('stockName', models.CharField(blank=True, max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('increaseRate', models.DecimalField(decimal_places=10, max_digits=32)),
                ('increaseRateStr', models.CharField(blank=True, max_length=100)),
                ('limitUpTime', models.CharField(max_length=30)),
                ('sections', models.CharField(max_length=300)),
                ('klineType', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AlterModelOptions(
            name='stocklimitup',
            options={'ordering': ('rank',)},
        ),
        migrations.AddField(
            model_name='stocklimitup',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
