# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20180523_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockincreasefastwithamount',
            options={'ordering': ('-time',)},
        ),
        migrations.AddField(
            model_name='stockincreasefastwithamount',
            name='time',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
