# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_stockamountrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockamountrate',
            name='amountRate',
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
    ]
