# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_auto_20180524_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOccupationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('stockId', models.CharField(max_length=32)),
                ('stockName', models.CharField(max_length=100)),
                ('occupationRate', models.DecimalField(decimal_places=4, max_digits=32)),
                ('turnoverRate', models.DecimalField(decimal_places=4, max_digits=32)),
            ],
            options={
                'ordering': ('-occupationRate',),
            },
        ),
    ]
