# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_stockoccupationrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('stockId', models.CharField(max_length=32)),
                ('stockName', models.CharField(max_length=100)),
                ('openPrice', models.DecimalField(decimal_places=2, max_digits=32)),
                ('competeAmout', models.DecimalField(decimal_places=2, max_digits=32)),
                ('competeVol', models.DecimalField(decimal_places=2, max_digits=32)),
                ('openIncreaseRate', models.DecimalField(decimal_places=10, max_digits=32)),
                ('openIncreaseRateStr', models.CharField(max_length=100)),
                ('capitalStock', models.DecimalField(decimal_places=2, max_digits=32)),
                ('openIncreaseRate4days', models.DecimalField(decimal_places=10, max_digits=32)),
                ('openIncreaseRate4daysStr', models.CharField(max_length=100)),
                ('oneType', models.CharField(max_length=1)),
                ('marketValue', models.DecimalField(decimal_places=2, max_digits=32)),
                ('isST', models.CharField(max_length=1)),
                ('datetime', models.CharField(max_length=32)),
                ('openIncreaseRateLastDay', models.DecimalField(decimal_places=10, max_digits=32)),
                ('openIncreaseRateLastDayStr', models.CharField(max_length=100)),
                ('openIncreaseRateLast2Day', models.DecimalField(decimal_places=10, max_digits=32)),
                ('openIncreaseRateLast2DayStr', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-competeAmout',),
            },
        ),
    ]
