# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_stockauction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockauction',
            old_name='openIncreaseRate4days',
            new_name='increaseRate4days',
        ),
        migrations.RenameField(
            model_name='stockauction',
            old_name='openIncreaseRate4daysStr',
            new_name='increaseRate4daysStr',
        ),
        migrations.RenameField(
            model_name='stockauction',
            old_name='openIncreaseRateLast2Day',
            new_name='increaseRateLast2Day',
        ),
        migrations.RenameField(
            model_name='stockauction',
            old_name='openIncreaseRateLast2DayStr',
            new_name='increaseRateLast2DayStr',
        ),
        migrations.RenameField(
            model_name='stockauction',
            old_name='openIncreaseRateLastDay',
            new_name='increaseRateLastDay',
        ),
        migrations.RenameField(
            model_name='stockauction',
            old_name='openIncreaseRateLastDayStr',
            new_name='increaseRateLastDayStr',
        ),
    ]
