# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_stockklinemode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTradeDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('isTradeDay', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
