# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_stocktradeday'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockId', models.CharField(max_length=32)),
                ('stockName', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'ordering': ('stockId',),
            },
        ),
        migrations.CreateModel(
            name='StockMarketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockId', models.CharField(max_length=32)),
                ('stockName', models.CharField(max_length=100)),
                ('closeLastDay', models.DecimalField(decimal_places=2, max_digits=32)),
                ('openPrice', models.DecimalField(decimal_places=2, max_digits=32)),
                ('close', models.DecimalField(decimal_places=2, max_digits=32)),
                ('high', models.DecimalField(decimal_places=2, max_digits=32)),
                ('low', models.DecimalField(decimal_places=2, max_digits=32)),
                ('current', models.DecimalField(decimal_places=2, max_digits=32)),
                ('increaseRate', models.DecimalField(decimal_places=10, max_digits=32)),
                ('increaseRateStr', models.CharField(max_length=100)),
                ('vol', models.DecimalField(decimal_places=2, max_digits=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('amountRate', models.DecimalField(decimal_places=2, max_digits=32)),
                ('turnoverRate', models.DecimalField(decimal_places=2, max_digits=32)),
                ('isStop', models.CharField(default='N', max_length=1)),
            ],
            options={
                'ordering': ('stockId',),
            },
        ),
    ]
