# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_stockinfo_stockmarketinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='amountRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='closeLastDay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='increaseRate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='openPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='turnoverRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='stockmarketinfo',
            name='vol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
    ]
