# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_auto_20180529_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='industry',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='mainBusiness',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='website',
            field=models.CharField(default='', max_length=300),
        ),
    ]
