# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_auto_20180611_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='industry',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='mainBusiness',
            field=models.CharField(default='', max_length=500),
        ),
    ]
