# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_auto_20180611_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='mainBusiness',
            field=models.CharField(default='', max_length=800),
        ),
    ]
