# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_auto_20180612_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='industry',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='mainBusiness',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
