# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-02 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_auto_20180612_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockklinemode',
            name='islandReversalFlag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
