# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-06 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_stockklinemode_islandreversalflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionInfoTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionId', models.CharField(max_length=300, null=True)),
                ('sectionName', models.CharField(max_length=300)),
                ('desc', models.TextField(null=True)),
            ],
            options={
                'ordering': ('-sectionName',),
            },
        ),
        migrations.CreateModel(
            name='StockSectionTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=300)),
                ('stockId', models.CharField(max_length=300)),
                ('stockName', models.CharField(max_length=300)),
                ('stockId2', models.CharField(max_length=300, null=True)),
                ('sectionId', models.CharField(max_length=300, null=True)),
            ],
            options={
                'ordering': ('-sectionName',),
            },
        ),
    ]
