# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-16 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_auto_20180707_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('stockId', models.CharField(max_length=32)),
                ('stockName', models.CharField(max_length=100)),
                ('factor', models.CharField(max_length=1000)),
                ('factorCount', models.IntegerField(default=0)),
                ('islandReversalFlag', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
