# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-16 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_stockfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfactor',
            name='competeAmout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='stockfactor',
            name='limitUpRank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockfactor',
            name='limitUpTime',
            field=models.CharField(default='', max_length=32),
        ),
    ]
