# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_auto_20180716_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.CharField(max_length=32)),
                ('stockId', models.CharField(max_length=32)),
                ('stockName', models.CharField(max_length=100)),
                ('orderPrice', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('orderQuantity', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ('-datatime',),
            },
        ),
    ]
