# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_orderlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlog',
            options={'ordering': ('-datetime',)},
        ),
        migrations.RenameField(
            model_name='orderlog',
            old_name='datatime',
            new_name='datetime',
        ),
    ]
