# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_auto_20180726_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='request',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='response',
            field=models.CharField(default='', max_length=512),
        ),
    ]
