# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.CharField(max_length=32)),
                ('endtime', models.CharField(max_length=32)),
                ('taskName', models.CharField(max_length=256)),
                ('taskResult', models.CharField(max_length=32)),
                ('errorMessage', models.CharField(max_length=512)),
                ('updateRecordNum', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-starttime',),
            },
        ),
    ]
